version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ../model:/app/model
      - ../data/processed:/app/data/processed
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
